let cfg=null;const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}
function fmtBytes(n){if(!n)return'0 B';let u=['B','KB','MB','GB','TB'],i=0;while(n>1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]}
async function api(url,opt){let r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text());return r.json()}
async function refresh(){try{let s=await api('/api/state');$('storage').textContent=`Liber: ${fmtBytes(s.storage.free)} / ${fmtBytes(s.storage.total)}`;let g=$('grid');g.innerHTML='';s.cameras.forEach(c=>{let el=document.createElement('article');el.className='card';el.innerHTML=`<div class="card-head"><div><b>${esc(c.name)}</b><span class="dot"></span></div><span class="badge ${c.recording?'rec':''}">${c.motion?'MIȘCARE':(c.recording?'REC':'LIVE')}</span></div><div class="video"><img src="/api/mjpeg/${c.id}" alt="live"><div class="overlay"><span>LIVE • RTSP local</span></div></div><div class="card-foot"><button onclick="startRec(${c.id})">REC</button><button onclick="stopRec(${c.id})">STOP</button><button onclick="snap(${c.id})">Captură</button></div>`;g.appendChild(el)})}catch(e){console.error(e)}}
async function startRec(i){await api(`/api/record/${i}/start`,{method:'POST'});refresh()}async function stopRec(i){await api(`/api/record/${i}/stop`,{method:'POST'});refresh()}async function snap(i){let r=await fetch(`/api/snapshot/${i}`),b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`camera-${i+1}-${Date.now()}.jpg`;a.click();URL.revokeObjectURL(a.href)}
async function loadArchive(){let rows=await api('/api/recordings'),q=($('search').value||'').toLowerCase();rows=rows.filter(x=>!q||(x.name+x.camera).toLowerCase().includes(q));$('archiveList').innerHTML=rows.map(x=>{let p=encodeURIComponent(x.path).replaceAll('%2F','/');return `<div class="record"><div><b>${esc(x.camera)}</b><div class="muted">${esc(x.mtime)} • ${fmtBytes(x.size)}</div></div><span><a target="_blank" href="/api/play/${p}">▶ Player</a> &nbsp; <a href="/api/file/${p}">Download</a></span></div>`}).join('')||'<div class="empty">Nu există înregistrări.</div>'}
async function loadSettings(){cfg=await api('/api/config');$('record_root').value=cfg.record_root||'';$('web_port').value=cfg.web_port||8765;$('ffmpeg_path').value=cfg.ffmpeg_path||'ffmpeg';$('record_mode').value=cfg.record_mode||'continuous';$('segment_minutes').value=cfg.segment_minutes||10;$('retention_days').value=cfg.retention_days||30;$('min_free_gb').value=cfg.min_free_gb||20;$('motion_enabled').value=cfg.motion?.enabled?'1':'0';$('motion_threshold').value=cfg.motion?.threshold??12;$('motion_fraction').value=cfg.motion?.min_changed_fraction??.02;$('motion_cooldown').value=cfg.motion?.cooldown_seconds??15;$('cams').innerHTML=cfg.cameras.map((c,i)=>`<div class="camrow"><input class="cn" data-i="${i}" value="${esc(c.name)}"><input class="cu" data-i="${i}" value="${esc(c.url)}"><input class="cp" data-i="${i}" type="password" value="${esc(c.password)}" placeholder="parola RTSP"></div>`).join('')}
async function saveSettings(){let cams=cfg.cameras.map((c,i)=>({name:document.querySelector(`.cn[data-i="${i}"]`).value,url:document.querySelector(`.cu[data-i="${i}"]`).value,username:c.username||'admin',password:document.querySelector(`.cp[data-i="${i}"]`).value}));let motion={...(cfg.motion||{}),enabled:$('motion_enabled').value==='1',threshold:+$('motion_threshold').value,min_changed_fraction:+$('motion_fraction').value,cooldown_seconds:+$('motion_cooldown').value};let body={...cfg,ffmpeg_path:$('ffmpeg_path').value,record_root:$('record_root').value,web_port:+$('web_port').value,record_mode:$('record_mode').value,segment_minutes:+$('segment_minutes').value,retention_days:+$('retention_days').value,min_free_gb:+$('min_free_gb').value,motion,cameras:cams};await api('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});alert('Setări salvate.');refresh()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active');$('title').textContent=b.textContent;if(b.dataset.page==='archive')loadArchive();if(b.dataset.page==='settings')loadSettings()});refresh();setInterval(refresh,15000);setInterval(()=>{$('clock').textContent=new Date().toLocaleString('ro-RO')},1000);